version: '3.7'

networks:
  canary:

services:
  # Tests
  tavern:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    entrypoint: entrypoint.sh tavern -c /src/app/tavern_global_config_ct_test.yaml -p /src/app/api
    networks:
      - canary
  smoke:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    entrypoint: entrypoint.sh smoke -f smoke.json -u http://hms-canary:9088
    networks:
      - canary

  # Service under test
  hms-canary:
    build: .
    networks:
      - canary
    depends_on:
    - s3
    - private-image

  # Start up some services. For right now just want to pull artifacts from algol60
  s3:
    image: artifactory.algol60.net/docker.io/minio/minio:latest
    hostname: s3
    environment:
      MINIO_ACCESS_KEY: s3-access-key
      MINIO_SECRET_KEY: s3-secret-key
    command:  server /data
    ports:
      - "9000:9000"
    networks:
      - canary
  s3-init:
    image: artifactory.algol60.net/docker.io/minio/mc:latest
    hostname: s3-init
    environment:
      - MC_HOST_S3=http://s3-access-key:s3-secret-key@s3:9000
    command:  mb S3/sls
    depends_on:
      - s3
    networks:
      - canary


  private-image:
    image: artifactory.algol60.net/csm-docker-private/stable/csm-docker-sle-python:3.10

