name: Run Open-API Tavern Coverage
on:
  - push # Perform a build of the contents from the branch
  - pull_request # Perform a build after merging with the target branch
  - workflow_dispatch
jobs:
  build_and_release:
    # TODO
    uses: Cray-HPE/open-api-tavern-coverage/.github/workflows/run_open-api-tavern-coverage.yaml@CASMHMS-5597
    #the v1 tag exists now
    with:
      open-api-file: "api/openapi.yaml"
      tavern-file-dir: "test/ct/api"
      api-target-urls: "{canary_base_url}"
    secrets: inherit

