name: Run Integration Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run_integration_test:
    uses: Cray-HPE/hms-build-image-workflows/.github/workflows/run_integration_test.yaml@CASMHMS-6042-self-hosted-runner
    with:
      runs-on: ubuntu-latest
    secrets: inherit